Repository 13IEZ/glamping_back, pull requests merged in 2021-08, with the labels that each got.

#92 back-feature #91 Modified Model - Location and added new fixtures for…
  fixtures-code.js
  src/api/v1/models/Location.js
  src/api/v1/routes/users.js
  src/index.js
Labels: feature

#102 back-bug #101 While creating new Review I made fetching actual date a…
  src/api/v1/routes/reviews.js
Labels: bug

#104 back-feautre #98 Changed model Location and fixtures Location
  fixtures-code.js
  src/api/v1/models/Location.js
Labels: feature

#106 back-feature #76 for front tiket 175 side filtration
  .eslintrc
  fixtures-code.js
  src/api/v1/models/Factory.js
  src/api/v1/models/Product.js
  src/api/v1/routes/factories.js
  src/api/v1/routes/products.js
  src/index.js
  src/utils.js
Labels: feature

#110 back-feature #96 created CRUD actions in router piches
  src/api/v1/routes/piches.js
Labels: feature

#113 back-enhancement #111 add route for side filtering 217 front tiket
  package.json
  src/api/v1/models/Accomod.js
  src/api/v1/routes/products.js
Labels: enhancement

#115 back-feature #114 add jenkins CI/CD settings
  package.json
Labels: feature

#125 back-enhancement #121 change routes for adapt pagination for filtering
  src/api/v1/middleware/filter.js
  src/api/v1/models/ProductFilter.js
  src/api/v1/routes/products.js
Labels: enhancement

#130 back-feature #118 Created router - (reservations) and added CRUD func…
  src/api/v1/routes/piches.js
  src/api/v1/routes/reservations.js
  src/index.js
Labels: feature

#132 back-enhancement #131 change product page count in Store
  fixtures-code.js
  src/api/v1/routes/products.js
Labels: enhancement

#135 front-enhancement #134 Added functionallity in reviews.js to get all …
  src/api/v1/routes/reviews.js
Labels: enhancement

#138 back-feature #137 add functionality for front tiket 187
  fixtures-code.js
  src/api/v1/routes/piches.js
  src/api/v1/routes/products.js
Labels: feature

#140 Removed duplicate prod
  .eslintrc
  package.json
  src/api/v1/routes/products.js
Labels: bug

#145 back-feature #144 created functionallity of getting user's products
  src/api/v1/routes/products.js
Labels: feature

#153 back-feature #152 Added fuctionallity of fetching owner's reservation…
  src/api/v1/routes/locations.js
  src/api/v1/routes/reservations.js
Labels: feature

#155 Fetched reservations of accommodations
  src/api/v1/routes/reservations.js
Labels: feature
