Repository 13IEZ/glamping_back, pull requests merged in 2021-09, with the labels that each got.

#163 back-bug #162 fixed bug in the route
  src/api/v1/models/Accommodation.js
  src/api/v1/models/Application.js
  src/api/v1/routes/applications.js
Labels: bug

#165 back-feature #164 add middleware functionality for front tiket 298
  src/api/v1/middleware/filterAccomod.js
  src/api/v1/routes/accommodations.js
  src/utils.js
Labels: feature

#167 console.log in accomodations.js deleted
  .eslintrc
  src/api/v1/routes/accommodations.js
Labels: bug

#173 back-bug #172 fixed bug for model Product
  .eslintrc
  src/api/v1/models/Product.js
Labels: bug

#177 back-bug #176 Made edits according to the ticket
  fixtures-code.js
  public/uploads/belltent3.jpg
Labels: bug

#179 front-bug #178 add image files to fixtures
  public/uploads/geo1.jpg
  public/uploads/geo2.jpeg
  public/uploads/geo2.jpg
  public/uploads/yurta1.jpg
Labels: bug

#184 fixed bug
  package.json
  src/api/v1/routes/accommodations.js
  src/api/v1/routes/locations.js
  yarn.lock
Labels: bug

#187 added valudation to file(image)
  src/api/v1/routes/products.js
Labels: enhancement

#189 fixed bug
  src/api/v1/models/Application.js
  src/api/v1/routes/accommodations.js
  src/api/v1/routes/applications.js
  src/api/v1/routes/locations.js
  src/api/v1/routes/piches.js
  src/api/v1/routes/products.js
Labels: bug
